### ISSUE TITLE
SDL2 Github Link 404s

### ISSUE THREAD

**Issue by DTV96Calibre** [vitasdk/samples#22]
The sdl2 sample has a readme which contains this link "https://github.com/vitadev/SDL-Vita"
That link 404s. Has it been moved?

**Comment by devnoname120** [comment]
I think it's now https://github.com/xerpi/SDL-Vita.

**Comment by DTV96Calibre** [comment]
That's what @xyzz told me to use. Should we update the readme then or will the old repo be coming back?

**Comment by devnoname120** [comment]
We could just remove `README.MD` since SDL2 is installed by [install-all.sh](https://github.com/vitasdk/vdpm/blob/master/install-all.sh).

**Comment by devnoname120** [comment]
Fixed by https://github.com/vitasdk/samples/pull/23.
