### ISSUE TITLE
Sample 3 Net_http cant write file because it is unsafe 

### ISSUE THREAD

**Issue by devingDev** [vitasdk/samples#25]
Hello could someone change the folder from ux0:temp to ux0:data ? Because when I tried it didnt work, it gave me weird negative write byte numbers.
Someone told me its because its not an unsafe homebrew and I should change it to a folder which can be written to by safe homebrew. So pls change that as it wont work like that.

**Comment by devnoname120** [comment]
Feel free to make a pull request o change it.

**Comment by devingDev** [comment]
I pulled, edited it staged and comitted but i can not push . I think because I do not have permission. Im using a client on Android MGit maybe I am doing it wrong.

**Comment by devnoname120** [comment]
@devingDev Create a fork, push to your fork, and then open a pull request.

**Comment by devnoname120** [comment]
Fixed by #27.
