### ISSUE TITLE
can you add a sample about loading and playing audio files?

### ISSUE THREAD

**Issue by readlnh** [vitasdk/samples#26]
I'm a beginner,and i have no idea about how to get audio working on the vita.The audio sample is not enough for me.Can you add a sample about: 
1.Load the audio file's audio data into a buffer (somehow)
2.play it
Can you add a sample about how to load the mp3 and play it?
Sorry for my poor english

**Comment by devnoname120** [comment]
Decoding a MP3 and playing it using the Vita API is a very complicated task.

I suggest you instead to decode your MP3 to PCM using libmad, and feed that decoded PCM to `sceAudioOutOutput()`. You can take a look at the audio sample to see how to use this function.

**Comment by readlnh** [comment]
Thank you very much, i will have a try.

**Comment by devnoname120** [comment]
@xyzz has ported [soloud](http://sol.gfxile.net/soloud/) to the PS Vita. Just run `./install-all.sh` again and you should be able to use this library.

**Comment by devnoname120** [comment]
Fixed in https://github.com/vitasdk/samples/commit/e140147487c235d00d7ff0d868ad627f2fdfa2e4.

**Comment by readlnh** [comment]
Thank you very much!

**Comment by yne** [comment]
@devnoname120  Could you consider https://github.com/vitasdk/samples/commit/e140147487c235d00d7ff0d868ad627f2fdfa2e4#commitcomment-23168649

**Comment by devnoname120** [comment]
@yne Sure, here it is: https://github.com/vitasdk/samples/commit/2cd56106808a761d56ae5f7ac619c0eab64c3200
