### ISSUE TITLE
New DebugScreeen implementation (was: "Missing psvDebugScreenClear() function")

### ISSUE THREAD

**Issue by windsurfer1122** [vitasdk/samples#50]
The sample "prx_loader" uses the function `psvDebugScreenClear()` which is not defined in any header file or library.
Did this function get lost somewhen? Or can it be added to the Vita SDK for general usage?

On the net I found the following code in different projects (mostly in a file called graphics.c):
```c
void psvDebugScreenClear(int bg_color)
{
	gX = gY = 0;
	int i;
	color_t *pixel = (color_t *)getVramDisplayBuffer();
	for(i = 0; i < SCREEN_WIDTH * SCREEN_HEIGHT; i++) {
		pixel->rgba = bg_color;
		pixel++;
	}
}
```

[1] https://github.com/dots-tb/rePatch-reDux0/blob/master/rePatchAIDs/graphics.c

**Comment by Rinnegatamante** [comment]
That's not the only issue with that sample in particular. It refers to an old vitasdk version. The sample itself should be updated.

**Comment by windsurfer1122** [comment]
@Rinnegatamante Thanks for the insight.

I investigated further and recognized that `psvDebugScreenClear()` was transformed to the macro `CLEARSCRN`. The code of the macro is much slower than the old one for the full screen, where lines and columns do not matter (complete screen vs. rectangular block).

Additionally I wonder why the debug screen code is inside a header and has several static definitions.

Currently adapting the old `psvDebugScreenClear()` function, plus splitting debug screen code and defines into separate code and header files.

**Comment by windsurfer1122** [comment]
Adapted `psvDebugScreenClear()` to current state of debug screen code.
Put debug screen code into a .c file while still keeping the possibility to include it.
Fixed typos, sanitized some macros, prepared macro for font scaling.

All `debugScreen*.(h|c)` files are still in common folder.
Just have to list `../common/debugScreen.c` in `add_executable()`.

For other projects all `debugScreen*.c` files can also be put into a `src` folder and all `debugScreen*.h` files into an `inc(lude|)` folder.
[common_debugScreen_20190718.zip](https://github.com/vitasdk/samples/files/3408464/common_debugScreen_20190718.zip)

Next will be to adopt the font scaler to it. Like `debug_put_char_32()` of https://github.com/TheOfficialFloW/h-encore/blob/master/bootstrap/scr_printf.c

**Comment by yne** [comment]
The `debugScreen.h` is [ANSI compatible](https://en.wikipedia.org/wiki/ANSI_escape_code). So please stop using all those `psvDebugScreenSet{F,B}gColor` / `psvDebugScreenClear` functions and just use escape sequence while calling printf.

See: https://github.com/vitasdk/samples/blob/master/debug_print/src/main.c

**Comment by windsurfer1122** [comment]
@yne Thanks for the explanation. Never had to deal with CSI sequences back in my C days (10+ years ago). Will re-adapt.

**Comment by windsurfer1122** [comment]
I enhanced and fixed some bugs in the current debugScreen implementation.
Also checked all samples to compile cleanly and correctly use CSI sequences.
Maybe the maintainers can consider accpeting these changes for the Vita SDK.

File: [samples-fixes-enhancements.zip](https://github.com/vitasdk/samples/files/3414713/samples-fixes-enhancements.zip)

debugScreen
-----------
* Splitted code and shared definitions into .c and .h file, so it can be used in bigger projects with multiple source files.
  C++ projects still need to include the code once(!) into another source file (e.g. main.cpp), for this define DEBUG_SCREEN_CODE_INCLUDE before including the debugScreen header file.
* Fixed CSI sequences 0J and 1J. Enhanced sample debugscreen cases to show the issue.
* Added documentation.
* Added functions to get/set font.
* Added function to scale a font by 2.
* Enhanced bitmap routines to work also with not byte-aligned glyphs.
  * Enhanced HTML bitmap editor to work also with not byte-aligned glyphs.
* Extended sample debugscreen to test more cases and demonstrate new functions.
* Sanitized macro usage.
* Fixed typos.

Samples in C
------------
* Added "../common/debugScreen.c" in CMakeLists.txt to the project executables:
  * audio
  * ctrl
  * debug_print
  * debugscreen
  * hello_world
  * microphone
  * motion
  * net_http
  * net_http_bsd
  * power
  * rtc
  * socket_ping
  * touch

Samples in C++
--------------
* Defined DEBUG_SCREEN_CODE_INCLUDE in main.cpp
  * net_libcurl
  * soloud

Sample camera
-------------
* Added missing include <psp2/kernel/processmgr.h> for sceKernelExitProcess().

Sample microphone
-----------------
* Added missing include string.h for memset() and memcpy().
* Changed direct access to coordX/Y to CSI sequences.

Sample net_http_bsd
-------------------
* Changed direct access to font to new functions.

Sample power
------------
* Added missing include stdio.h for FILE, fopen(), fclose().
* Added missing include string.h for memset().

**Comment by yne** [comment]
Nice job, it's always nice to see some unification.
What was the issue from having a single self-exclusive .h file ?
The power sample is definitely strange:
- the fopen shall not succeed to create a new file unless `w+`
- the created `fd` is unused

**Comment by windsurfer1122** [comment]
My private project will have 2 or 3 different source files (*.c) and all of them will create some debugScreen output. If the old "debugScreen.h" is included on all 3 files, I will have duplicate code in my .o files and/or linker issues.

Side note:
When checking my own bug I also found out that the color creation for CSI m is a little bit off:
* CSI 2m is actually "dark" color (faint/decreased intensity) and not "normal" color/intensity
* CSI 22m is "normal" color/intensity
* CSI 30-37/40-47/90-97/100-107m do not fit to CSI 1/2m implementation
* Naming is sometimes wrongly RGB although internally it is BGR.

So I'm currently fixing these, also implementing CSI 7m for "invert"/"reverse video" and optimze code on the way (guideline: always code like there is no compiler optimization).
My sample "debugscreen" became heavily colorful :)

**Comment by yne** [comment]
> I will have duplicate code in my .o files and/or linker issues.

Have you tried to change `psvDebugScreen{Init,Puts,Printf}` to `static` ?
In my tests it resolve the linking issue, and the code is not duplicated either, and it's still easy to include in small project (like all the vita samples).

> guideline: always code like there is no compiler optimization

Did you mean

> Trying to outsmart a compiler defeats much of the purpose of using one -- Kernighan

?

> So I'm currently fixing these, also implementing [...]

Let's hope those features and hand-crafted optimization won't add more bugs/bloat/complexity than the features they add

**Comment by windsurfer1122** [comment]
Don't want to outsmart or avoid the optimizer of the compiler (via pragmas, flags, etc.) as I never would assume that I'm smarter than those guys developing compilers.
Just doing calculations when necessary and where appropiate (e.g. either before or inside a loop).

Always try to keep code maintainable/clean, sanitized, straight forward and re-usable.

Just read all available docs for CSI sequences and hope to get it done the next days.

**Comment by windsurfer1122** [comment]
Updated earlier comment/post https://github.com/vitasdk/samples/issues/50#issuecomment-513560500 with updated implementation. Tested quite a lot and should be a solid implementation. Should be final.
Ready for review.

**Comment by yne** [comment]
You shall at least check `net_http_bsd` sample because it printf the result of http://rate.sx/ and http://wttr.in/ wich rely on those CSI codes.

**Comment by windsurfer1122** [comment]
@yne Will do when time permits, at least on Sunday.

**Comment by yne** [comment]
@windsurfer1122 nice :)
Any update about the `static` suggestion ?
If it's working, your PR shall be more simple (no `#include` or `CMake` changes)

**Comment by windsurfer1122** [comment]
Hiding internal functions via `static` is ok, but for shared functions this would be awkward.
The `static` suggestion would make the code local to the source (and its related binary object), therefore for each source file of a project the same code would be compiled and included into the final binary.
Will check if the current gcc is intelligent enough and recognizes the duplicate binary result. But that will be on sunday.

The only reason I found for including the code as it was before, was for C++, and that could be handled with a simple #define. 

The changes to the CPP source with `#define` and to the `CMakeLists.txt` are very minor from my point of view. Even for unexperienced C/C++ coders.
Is this still a pain in your stomache?

**Comment by yne** [comment]
> Is this still a pain in your stomache?

Nah I'm fine, I was just curious if the `static` version was also working in your situation.
The `.c`+`.h` is the most common practice, (even if It's not my cup of tea anymore, than you Bellard).
I'm okay to have it in c+h style, don't worry :).

**Comment by windsurfer1122** [comment]
I got an idea for a compromise, give me an hour.

**Comment by windsurfer1122** [comment]
My first pull request. Hope this is done correctly.
https://github.com/vitasdk/samples/pull/51

**Comment by windsurfer1122** [comment]
Updated pull request. Corrected header file for C++, so even less changes are needed in the C++ samples to the source code.

**Comment by windsurfer1122** [comment]
Added via ded5780dfda5b5a9e7bf97be571123dc784d6cd5
